title: Unity Audio Manager
email: noreply@users.github.com
description: Used to play/change/stop/mute/… sounds at certain circumstances or events in 2D and 3D simply via. code.
logo: /logo.png
github_username: MathewHDYT
color_scheme: dark

# Build settings
remote_theme: pmarsceill/just-the-docs
#theme: "just-the-docs"

aux_links:
  "Unity Audio Manager on GitHub":
    - "//github.com/MathewHDYT/Unity-Audio-Manager"
