title: Unity Audio Manager
email: noreply@users.github.com
logo: /logo.png
color_scheme: dark

# Build settings
remote_theme: pmarsceill/just-the-docs
#theme: "just-the-docs"

aux_links:
  "Unity Audio Manager on GitHub":
    - "//github.com/MathewHDYT/Unity-Audio-Manager"
