coverage:
  status:
    project:
      default: # This can be anything, but it needs to exist as the name
        target: auto
        threshold: 5%
        base: auto
        if_ci_failed: ignore # Success, failure, error, ignore
    patch:
      default: # This can be anything, but it needs to exist as the name
        target: auto
        threshold: 5%
        base: auto
        if_ci_failed: ignore # Success, failure, error, ignore
ignore:
  - "**/Tests/**/*"  # Recursively ignore test folder
  - "**/Scripts/AudioManager/Settings/ShowIfAttributeDrawer.cs" # Ignore file that can't be unittested
  - "**/Scripts/AudioManager/Settings/AudioSourceSettingEditor.cs"
  - "**/Scripts/*.cs" # Ignore files that are only used for the example project and not included in the AudioManager source code
 